"""
YOLOv8 Training Script for Marine Debris Detection
OceanGuard Project - Pengolahan Citra Digital

Usage:
    python train.py                          # Train with default settings
    python train.py --model yolov8s.pt       # Use small model
    python train.py --epochs 200 --batch 8   # Custom epochs and batch size
"""

import argparse
import os
from pathlib import Path
from datetime import datetime

try:
    from ultralytics import YOLO
except ImportError:
    print("ERROR: ultralytics not installed.")
    print("Run: pip install ultralytics")
    exit(1)


def parse_args():
    parser = argparse.ArgumentParser(
        description="Train YOLOv8 for marine debris detection"
    )
    parser.add_argument(
        "--model",
        type=str,
        default="yolov8n.pt",
        help="Pretrained model to use (yolov8n.pt, yolov8s.pt, yolov8m.pt)",
    )
    parser.add_argument(
        "--data",
        type=str,
        default=None,
        help="Path to dataset YAML config file",
    )
    parser.add_argument(
        "--epochs",
        type=int,
        default=100,
        help="Number of training epochs (default: 100)",
    )
    parser.add_argument(
        "--batch",
        type=int,
        default=16,
        help="Batch size (default: 16)",
    )
    parser.add_argument(
        "--imgsz",
        type=int,
        default=640,
        help="Input image size (default: 640)",
    )
    parser.add_argument(
        "--patience",
        type=int,
        default=20,
        help="Early stopping patience (default: 20)",
    )
    parser.add_argument(
        "--device",
        type=str,
        default="",
        help="Device to train on ('' for auto, 'cpu', '0', '0,1')",
    )
    parser.add_argument(
        "--name",
        type=str,
        default=None,
        help="Run name for saving results",
    )
    return parser.parse_args()


def create_dataset_yaml(data_dir: Path) -> str:
    """
    Create a dataset YAML config file for YOLOv8 training.
    
    Expected directory structure:
    data/
    ├── train/
    │   ├── images/
    │   └── labels/
    ├── val/
    │   ├── images/
    │   └── labels/
    └── test/
        ├── images/
        └── labels/
    """
    yaml_path = data_dir / "dataset.yaml"

    yaml_content = f"""# OceanGuard Marine Debris Dataset
# Auto-generated by train.py

path: {data_dir.absolute()}
train: train/images
val: val/images
test: test/images

# Number of classes
nc: 6

# Class names
names:
  0: plastic
  1: bottle
  2: can
  3: net_rope
  4: bag
  5: others
"""

    with open(yaml_path, "w") as f:
        f.write(yaml_content)

    print(f"✅ Dataset YAML created: {yaml_path}")
    return str(yaml_path)


def train(args):
    """Main training function"""

    print("=" * 60)
    print("🌊 OceanGuard - YOLOv8 Marine Debris Detection Training")
    print("=" * 60)

    # Setup paths
    project_root = Path(__file__).parent.parent
    data_dir = project_root / "data"
    weights_dir = project_root / "weights"
    weights_dir.mkdir(exist_ok=True)

    # Dataset config
    if args.data:
        data_yaml = args.data
    else:
        if not data_dir.exists():
            print(f"\n❌ Data directory not found: {data_dir}")
            print("\nPlease prepare your dataset with this structure:")
            print("  model/data/")
            print("  ├── train/")
            print("  │   ├── images/  (training images)")
            print("  │   └── labels/  (YOLO format .txt labels)")
            print("  ├── val/")
            print("  │   ├── images/  (validation images)")
            print("  │   └── labels/  (YOLO format .txt labels)")
            print("  └── test/")
            print("      ├── images/  (test images)")
            print("      └── labels/  (YOLO format .txt labels)")
            print("\nOr run preprocess.py to prepare the dataset first.")
            return

        data_yaml = create_dataset_yaml(data_dir)

    # Run name
    if args.name is None:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        run_name = f"oceanguard_{timestamp}"
    else:
        run_name = args.name

    print(f"\n📋 Training Configuration:")
    print(f"   Model:      {args.model}")
    print(f"   Dataset:    {data_yaml}")
    print(f"   Epochs:     {args.epochs}")
    print(f"   Batch Size: {args.batch}")
    print(f"   Image Size: {args.imgsz}")
    print(f"   Patience:   {args.patience}")
    print(f"   Device:     {args.device or 'auto'}")
    print(f"   Run Name:   {run_name}")
    print()

    # Load model
    print(f"📦 Loading pretrained model: {args.model}")
    model = YOLO(args.model)

    # Start training
    print(f"\n🚀 Starting training...")
    results = model.train(
        data=data_yaml,
        epochs=args.epochs,
        batch=args.batch,
        imgsz=args.imgsz,
        patience=args.patience,
        device=args.device if args.device else None,
        name=run_name,
        project=str(project_root / "runs"),
        
        # Optimization
        optimizer="AdamW",
        lr0=0.01,
        lrf=0.01,
        weight_decay=0.0005,
        warmup_epochs=3,
        
        # Augmentation
        hsv_h=0.015,
        hsv_s=0.7,
        hsv_v=0.4,
        degrees=10.0,
        translate=0.1,
        scale=0.5,
        fliplr=0.5,
        flipud=0.2,
        mosaic=1.0,
        mixup=0.1,
        
        # Saving
        save=True,
        save_period=10,
        plots=True,
        verbose=True,
    )

    # Copy best weights to weights directory
    runs_dir = project_root / "runs" / run_name
    best_weights = runs_dir / "weights" / "best.pt"
    
    if best_weights.exists():
        import shutil
        dest = weights_dir / "best.pt"
        shutil.copy2(best_weights, dest)
        print(f"\n✅ Best weights copied to: {dest}")

    print(f"\n🎉 Training completed!")
    print(f"   Results saved to: {runs_dir}")
    print(f"   Best weights: {weights_dir / 'best.pt'}")

    return results


if __name__ == "__main__":
    args = parse_args()
    train(args)
